# TouchDesigner Python Script - Set Path-Tracer Parameter Help Text

op_name = target

# Page: Path Tracer
op_name.par.Enabletracing.help = "Master toggle for path tracing rendering."
op_name.par.Enablehybridtracing.help = "Enables hybrid tracing mode that renders both the voxel tracer and geometry path tracing together."
op_name.par.Reset.help = "Pulse to reset progressive accumulation and restart rendering."
op_name.par.Lockinput.help = "Freeze input geometry to prevent updates during progressive rendering."
op_name.par.Progressiverendering.help = "Accumulate samples over time for noise-free convergence."
op_name.par.Projectongeometry.help = "Projects the path traced result onto the input geometry surface."
op_name.par.Rendertop.help = "Reference to Render TOP providing camera and viewport settings that the path tracer will render to."
op_name.par.Raysperpixel.help = "Number of rays cast per pixel per frame."
op_name.par.Maxbounces.help = "Maximum ray bounce depth for global illumination."
op_name.par.Rayoffset.help = "Offset distance for ray origins to prevent self-intersection artifacts."
op_name.par.Focallength.help = "Distance from camera where objects are in sharp focus."
op_name.par.Aperture.help = "Camera aperture size for depth of field."
op_name.par.Showfocalplane.help = "Displays the focal plane in the viewport for visualization."
op_name.par.Focalplanesize.help = "Size of the focal plane visualization."

# Page: Material
op_name.par.Attrclass.help = "Selects which attribute class the material properties are applied to."
op_name.par.Overrideifexists.help = "Apply material parameters even when geometry has existing material attributes."
op_name.par.Basecolorr.help = "Diffuse albedo color."
op_name.par.Metallic.help = "Metallic appearance."
op_name.par.Roughness.help = "Surface roughness."
op_name.par.Specular.help = "Specular reflection strength for dielectrics."
op_name.par.Specularcolorr.help = "Tint specular reflection with color."
op_name.par.Anisotropic.help = "Anisotropic highlight stretching."
op_name.par.Anisotropicrot.help = "Rotation angle for anisotropic highlights."
op_name.par.Subsurface.help = "Subsurface scattering amount for translucent materials like skin or wax."
op_name.par.Sheen.help = "Soft velvet-like reflection for fabrics and cloth."
op_name.par.Sheencolorr.help = "Tint sheen reflection with color."
op_name.par.Clearcoat.help = "Secondary specular layer for car paint or lacquered surfaces."
op_name.par.Clearcoatgloss.help = "Glossiness of clearcoat layer."
op_name.par.Ior.help = "Index of refraction for dielectrics."
op_name.par.Transmission.help = "Light transmission through surface for glass and transparent materials."
op_name.par.Dispersion.help = "Chromatic dispersion amount for refractive materials."
op_name.par.Emissionr.help = "Emissive color for self-illuminating surfaces."

# Page: Voxel Tracer
op_name.par.Enablevoxeltracing.help = "Master toggle for voxel tracing rendering."
op_name.par.Rendermode.help = "Selects the voxel rendering technique."
op_name.par.Rendermodemap.help = "3D texture map that blends between isosurface and volume rendering."
op_name.par.Stepsizescale.help = "Multiplier for ray marching step size through the volume."
op_name.par.Usecustombounds.help = "Enables custom bounding box for the voxel volume."
op_name.par.Lowerboundsx.help = "Minimum XYZ coordinates of the voxelization volume."
op_name.par.Upperboundsx.help = "Maximum XYZ coordinates of the voxelization volume."
op_name.par.Xord.help = "Sets the order of scale, rotate, and translate operations for the voxel volume transform."
op_name.par.Rord.help = "Sets the order of rotation operations for the voxel volume transform."
op_name.par.Tx.help = "Translation of the voxel volume in world space."
op_name.par.Rx.help = "Rotation of the voxel volume in degrees."
op_name.par.Sx.help = "Scale of the voxel volume per axis."
op_name.par.Px.help = "Pivot point for the voxel volume transform."
op_name.par.Scale.help = "Uniform scale factor applied to the voxel volume."
op_name.par.Densityscale.help = "Multiplier for volumetric density values."
op_name.par.Absorptionr.help = "Color filter applied to light absorbed within the volume."
op_name.par.Scatteringcoeff.help = "Controls the amount of light scattered within the volume."
op_name.par.Thresholdchan.help = "Selects which texture channel to use for isosurface threshold evaluation."
op_name.par.Surfacethreshold.help = "Density value at which the isosurface is extracted from the volume."
op_name.par.Normalsmoothing.help = "Smoothing factor for computed surface normals on the isosurface."
op_name.par.Metallicmap.help = "3D texture map for metallic material property on the isosurface."
op_name.par.Roughnessmap.help = "3D texture map for roughness material property on the isosurface."
op_name.par.Specularmap.help = "3D texture map for specular reflection strength on the isosurface."
op_name.par.Specularcolormap.help = "3D texture map for specular color tint on the isosurface."
op_name.par.Anisotropicmap.help = "3D texture map for anisotropic highlight stretching on the isosurface."
op_name.par.Anisotropicrotmap.help = "3D texture map for anisotropic highlight rotation on the isosurface."
op_name.par.Subsurfacemap.help = "3D texture map for subsurface scattering on the isosurface."
op_name.par.Sheenmap.help = "3D texture map for sheen reflection on the isosurface."
op_name.par.Sheencolormap.help = "3D texture map for sheen color tint on the isosurface."
op_name.par.Clearcoatmap.help = "3D texture map for clearcoat layer on the isosurface."
op_name.par.Clearcoatglossmap.help = "3D texture map for clearcoat glossiness on the isosurface."
op_name.par.Iormap.help = "3D texture map for index of refraction on the isosurface."
op_name.par.Transmissionmap.help = "3D texture map for light transmission on the isosurface."
op_name.par.Dispersionmap.help = "3D texture map for chromatic dispersion on the isosurface."
op_name.par.Emissionmap.help = "3D texture map for emissive color on the isosurface."

# Page: Lights
op_name.par.Enableenv.help = "Enable image-based lighting from environment map."
op_name.par.Environmentmap.help = "HDR environment texture."
op_name.par.Envmapintensity.help = "Multiplier for environment light contribution."
op_name.par.Renderenv.help = "Show environment map in background when rays miss geometry."
op_name.par.Enabledirectlight.help = "Enable direct lighting."
op_name.par.Texturemapresx.help = "Resolution of the texture maps used for direct light evaluation."
op_name.par.Lights.help = "Sequence of light sources."
op_name.par.Lights0lightcomp.help = "Reference to a POPX Light tool defining light properties."

# Page: Post
op_name.par.Enabletonemap.help = "Apply tone mapping to convert HDR output to display range."
op_name.par.Exposure.help = "Exposure multiplier for tone mapping."
op_name.par.Gamma.help = "Gamma correction value for tone mapping output."
op_name.par.Enablesvgf.help = "Enable SVGF denoiser for real-time noise reduction."
op_name.par.Colorboxscale.help = "Scale factor for the color bounding box used in temporal reprojection."
op_name.par.Maxhistory.help = "Maximum number of frames to accumulate in temporal history."
op_name.par.Normalthreshold.help = "Threshold for surface normal similarity in temporal reprojection."
op_name.par.Depththreshold.help = "Threshold for depth similarity in temporal reprojection."
op_name.par.Kernelradius.help = "Radius of the variance estimation kernel."
op_name.par.Varnormalsensitivity.help = "Sensitivity to surface normal differences in variance estimation."
op_name.par.Vardepthsensitivity.help = "Sensitivity to depth differences in variance estimation."
op_name.par.Passes.help = "Number of a-trous wavelet filter passes for spatial denoising."
op_name.par.Colorsensitivity.help = "Sensitivity to color differences in a-trous filtering."
op_name.par.Trousnormalsensitivity.help = "Sensitivity to surface normal differences in a-trous filtering."
op_name.par.Trousdepthsensitivity.help = "Sensitivity to depth differences in a-trous filtering."
op_name.par.Roughnesssensitivity.help = "Sensitivity to roughness differences in a-trous filtering."

# Page: Common
op_name.par.Freeextragpumem.help = "Free memory that has accumulated when output memory has grown and shrunk."

print("Path-Tracer parameter help text updated successfully!")
