# TouchDesigner Python Script - Set Relax Parameter Help Text

op_name = target

# Page: Relax
op_name.par.Group.help = "If there are input groups, specifying a group name in this field will cause this POPX to act only upon the group specified."
op_name.par.Solvermode.help = "Switches between Simple and Advect modes."
op_name.par.Relaxmethod.help = "Determines the relaxation algorithm: Neighbor (proximity-based search) or Field (voxel-based volume approach)."
op_name.par.Pointsupdatepop.help = "Reference to a POP node downstream in the network when Solver Mode is set to Advect. This reference will cause a feedback loop and re-injects the points next frame."
op_name.par.Dofalloff.help = "Enables falloff-based modulation of the relaxation effect."
op_name.par.Falloffattr.help = "Specifies which attribute to use for falloff values that modulate the relaxation strength."
op_name.par.Affectposition.help = "Enables relaxation forces to affect instance positions."
op_name.par.Relaxiters.help = "Number of relaxation passes to perform per frame."
op_name.par.Overrideradius.help = "Overrides the point radius used for overlap detection with a uniform value."
op_name.par.Radiusaxis.help = "Selects which axis of the PointScale attribute to use as the point radius."
op_name.par.Radiusscale.help = "Scale factor applied to the point radius for overlap detection."
op_name.par.Displayradius.help = "Displays the point radius as circles in the viewport."
op_name.par.Maxrelaxradius.help = "Maximum search distance for finding neighboring instances."
op_name.par.Distribution.help = "Determines the distribution method for neighbor point selection."
op_name.par.Numhashbuckets.help = "Number of hash buckets used for spatial hashing in neighbor search."
op_name.par.Maxneighbors.help = "Maximum number of neighboring instances to consider when using Neighbor method."
op_name.par.Maxaxisres.help = "Maximum voxel resolution along the longest axis when using Field method."
op_name.par.Kernelsize.help = "Size of the convolution kernel used for field-based relaxation."
op_name.par.Fieldlowerboundsx.help = "Lower bounds of the field volume when using Field method."
op_name.par.Fieldupperboundsx.help = "Upper bounds of the field volume when using Field method."
op_name.par.Relaxstrength.help = "Overall intensity of the relaxation effect."
op_name.par.Attractpositionx.help = "Position in 3D space that instances are attracted toward."
op_name.par.Attractstrength.help = "Strength of the attraction force toward the Attract Position."
op_name.par.Outputforceattribute.help = "Outputs the relaxation force vector as a point attribute."
op_name.par.Initializepulse.help = "Resets the Advect solver to initial state."
op_name.par.Startpulse.help = "Begins Advect solver simulation from the current state."
op_name.par.Play.help = "Toggles playback of the Advect solver simulation."
op_name.par.Steppulse.help = "Advances the Advect solver by one frame."

# Page: Collisions
op_name.par.Collisiontype.help = "Selects the collision geometry type for constraining instance movement."
op_name.par.Collisiondamping.help = "Amount of velocity dampening applied when instances collide with the collision geometry."
op_name.par.Solid.help = "Treats the collision geometry as a solid volume, preventing instances from passing through."
op_name.par.Project.help = "Projects instances onto the surface of the collision geometry."
op_name.par.Collisionpop.help = "Reference to a POP containing the collision geometry when using POP collision type."
op_name.par.Collisionoffset.help = "Offset distance from the collision surface to prevent z-fighting artifacts."
op_name.par.Sizex.help = "Size of the box collision geometry."
op_name.par.Radiusx.help = "Radius of the collision geometry per axis."
op_name.par.Cornerradius.help = "Radius of rounded corners on the box collision geometry."
op_name.par.Collisontop.help = "Reference to a TOP texture used as the collision field for SDF and texture collision types."
op_name.par.Usecustombounds.help = "Enables custom bounding box for the collision texture instead of using the texture's native bounds."
op_name.par.Lowerboundsx.help = "Lower bounds of the collision volume in world space."
op_name.par.Upperboundsx.help = "Upper bounds of the collision volume in world space."
op_name.par.Xord.help = "Sets the order of scale, rotate, and translate operations for the collision geometry transform."
op_name.par.Rord.help = "Sets the order of rotation operations for the collision geometry transform."
op_name.par.Tx.help = "Translation of the collision geometry in world space."
op_name.par.Rx.help = "Rotation of the collision geometry in degrees."
op_name.par.Sx.help = "Scale of the collision geometry per axis."
op_name.par.Px.help = "Pivot point for the collision geometry transform."
op_name.par.Scale.help = "Uniform scale factor applied to the collision geometry."
op_name.par.Displaygeo.help = "Shows the collision geometry in the viewport for visualization."
op_name.par.Displaycolorr.help = "Display color for the collision geometry visualization."

# Page: Common
op_name.par.Bypass.help = "Pass through the first input to the output unchanged."
op_name.par.Freeextragpumem.help = "Free memory that has accumulated when output memory has grown and shrunk."
op_name.par.Renderprimitives.help = "Toggles rendering of POPX Geometry or shows it as point instances only."
op_name.par.Converttoptprim.help = "Converts points to primitive points when Render Primitives is toggled off."
op_name.par.Srtrst.help = "Sets the transform order when using POPX Geometry as built-in TouchDesigner."

print("Relax parameter help text updated successfully!")
