# TouchDesigner Python Script - Set Move-Along-Curve Parameter Help Text

op_name = target

# Page: Move Along Curve
op_name.par.Group.help = "If there are input groups, specifying a group name in this field will cause."
op_name.par.Curve.help = "Reference to a POP for the curve to attach instances to when no second input is."
op_name.par.Displaycurve.help = "Visualizes the curve in the viewport."
op_name.par.Initializepulse.help = "Resets the simulation state to initial conditions."
op_name.par.Startpulse.help = "Begins the simulation from the current state."
op_name.par.Play.help = "Toggles simulation playback on or off when in Solver mode."
op_name.par.Steppulse.help = "Advances the simulation by one frame when in Solver mode."

# Page: Attach
op_name.par.Locktocurve.help = "Locks the initial attachment positions so they don't need to be recalculated."
op_name.par.Reattachtocurve.help = "Recomputes attachment points for all instances."
op_name.par.Primindex.help = "Specifies which primitive index to attach to when Curve Select Mode is set to."
op_name.par.Searchdistance.help = "Maximum distance for finding nearest attachment points when using Nearest Point."
op_name.par.Attachattr.help = "Specifies which attribute to use for determining attachment positions when."
op_name.par.Snaptocentroid.help = "Moves the centroid of all instances to the start of the curve before attaching."
op_name.par.Doorientsnap.help = "Applies orientation alignment when snapping centroid to curve start."
op_name.par.Maintainoffset.help = "Blend amount for maintaining the original offset distance from the curve."
op_name.par.Openoffsetramp.help = "Opens the internal offset ramp editor for customizing offset behavior along the."
op_name.par.Resetoffsetramp.help = "Resets the offset ramp to default values."
op_name.par.Offsettop.help = "Reference to an external TOP for offset control."
op_name.par.Maintainorientoffset.help = "Blend amount between the original orientation and the curve orientation."
op_name.par.Openorientoffsetramp.help = "Opens the internal orientation offset ramp editor."
op_name.par.Resetorientoffsetramp.help = "Resets the orientation offset ramp to default values."
op_name.par.Orienttop.help = "Reference to an external TOP for orientation offset."
op_name.par.Visualizeoffset.help = "Displays lines showing the offset between instances and their attachment points."
op_name.par.Fetchoffsetslines.help = "Creates a select POP with the selected offsets lines of the instances for."
op_name.par.Reorientinputcurve.help = "Enables reorientation of the input curve for better tangent and normal."
op_name.par.Inverttangent.help = "Reverses the tangent direction of the curve by 180 degrees."
op_name.par.Customfirsttangent.help = "Enables specification of a custom tangent vector at the start of the curve."
op_name.par.Twistcurveamount.help = "Amount of twist to apply to the curve orientation in degrees."
op_name.par.Opentwistcurveramp.help = "Opens the internal twist ramp editor for modulating twist along the curve."
op_name.par.Resettwistcurveramp.help = "Resets the twist ramp to default values."
op_name.par.Twistcurvetop.help = "Reference to an external TOP for twist control."
op_name.par.Twistpercurve.help = "Applies twist ramp per individual curve primitive when using multiple curves."
op_name.par.Resampledivs.help = "The number of divisions."
op_name.par.Resamplemaxdist.help = "Maximum distance between points."
op_name.par.Maxverts.help = "Sets the number of vertices to be allocated."
op_name.par.Maxtries.help = "Max number of iterations for binary search when linearly resampling."

# Page: Animate
op_name.par.Dofalloff.help = "Enables falloff-based modulation of animation effects."
op_name.par.Affectspeed.help = "Allows falloff values to modulate instance movement speed."
op_name.par.Affectrot.help = "Allows falloff values to modulate instance rotation alignment."
op_name.par.Falloffattr.help = "Specifies which attribute to use for falloff values that modulate animation."
op_name.par.Goal.help = "Target position along the curve for procedural animation in Simple mode."
op_name.par.Speed.help = "Global speed multiplier for instance movement along the curve in Solver mode."
op_name.par.Randomspeed.help = "Amount of random variation applied to each instance's speed."
op_name.par.Seedspeed.help = "Random seed value for speed randomization."
op_name.par.Reverse.help = "Reverses the direction of movement along the curve."
op_name.par.Aligntocurve.help = "Aligns instance orientation to follow the curve tangent direction."
op_name.par.Wrap.help = "Enables wrapping from the end of the curve back to the start for continuous."
op_name.par.Outputgoalattrs.help = "Outputs GoalU and CurveIndex attributes."
op_name.par.Twistamount.help = "Additional twist rotation applied during animation in degrees."
op_name.par.Opentwistramp.help = "Opens the internal twist ramp editor for animation twist modulation."
op_name.par.Resettwistramp.help = "Resets the animation twist ramp to default values."
op_name.par.Twisttop.help = "Reference to an external TOP for animation twist control."
op_name.par.Scalebygoal.help = "Enables scale modulation based on goal position along the curve."
op_name.par.Openscaleramp.help = "Opens the internal scale ramp editor for creating custom scale curves based on."
op_name.par.Resetscaleramp.help = "Resets the scale ramp to default values."
op_name.par.Scaletop.help = "Reference to an external TOP for scale control."
op_name.par.Acceleratebygoal.help = "Enables acceleration modulation based on goal position along the curve."
op_name.par.Openaccramp.help = "Opens the internal acceleration ramp editor for modulating speed along the."
op_name.par.Resetaccramp.help = "Resets the acceleration ramp to default values."
op_name.par.Acctop.help = "Reference to an external TOP for acceleration control."

# Page: Common
op_name.par.Bypass.help = "Pass through the first input to the output unchanged."
op_name.par.Freeextragpumem.help = "Free memory that has accumulated when output memory has grown and shrunk."
op_name.par.Renderprimitives.help = "Toggles rendering of POPX Geometry or shows it as point instances only."
op_name.par.Srtrst.help = "Sets the transform order when using POPX Geometry as built-in TouchDesigner."

print("Move-Along-Curve parameter help text updated successfully!")
