# TouchDesigner Python Script - Set Soft-Body Parameter Help Text

op_name = target

# Page: Soft Body
op_name.par.Targetupdatepop.help = "POP operator providing target geometry updates for the simulation."
op_name.par.Timescale.help = "Global time scale multiplier for the simulation speed."
op_name.par.Timestep.help = "Read-only display of effective timestep, equal to 1/FPS of TouchDesigner."
op_name.par.Substeps.help = "Number of simulation substeps per frame for improved stability."
op_name.par.Iterations.help = "Number of constraint solver iterations."
op_name.par.Initializepulse.help = "Pulse to initialize or reset the simulation."
op_name.par.Startpulse.help = "Pulse to start the simulation from its initial state."
op_name.par.Play.help = "Toggle to play or pause the simulation."
op_name.par.Steppulse.help = "Pulse to advance the simulation by one frame when paused."

# Page: Collisions
op_name.par.Enablegroundcollision.help = "Enable collision with an infinite ground plane."
op_name.par.Groundpositionx.help = "Position of the ground plane in world space."
op_name.par.Groundmargin.help = "Collision margin distance from the ground plane surface."
op_name.par.Displayground.help = "Visualize the ground plane in the viewport."
op_name.par.Enablebboxcollision.help = "Enable collision with a bounding box volume."
op_name.par.Bbox.help = "A reference to a POP defining the bounding box collision bounds."
op_name.par.Bboxmargin.help = "Collision margin distance from the bounding box surface."
op_name.par.Displaybbox.help = "Visualize the bounding box in the viewport."
op_name.par.Collisiontype.help = "Selects the collision geometry type for constraining instance movement."
op_name.par.Collisiondamping.help = "Amount of velocity dampening applied when instances collide with the collision geometry."
op_name.par.Solid.help = "Treats the collision geometry as a solid volume, preventing instances from passing through."
op_name.par.Project.help = "Projects instances onto the surface of the collision geometry."
op_name.par.Collisionpop.help = "Reference to a POP containing the collision geometry when using POP collision type."
op_name.par.Collisionoffset.help = "Offset distance from the collision surface to prevent z-fighting artifacts."
op_name.par.Sizex.help = "Size of the box collision geometry."
op_name.par.Radiusx.help = "Radius of the collision geometry per axis."
op_name.par.Cornerradius.help = "Radius of rounded corners on the box collision geometry."
op_name.par.Collisontop.help = "Reference to a TOP texture used as the collision field for SDF and texture collision types."
op_name.par.Usecustombounds.help = "Enables custom bounding box for the collision texture instead of using the texture's native bounds."
op_name.par.Lowerboundsx.help = "Lower bounds of the collision volume in world space."
op_name.par.Upperboundsx.help = "Upper bounds of the collision volume in world space."
op_name.par.Xord.help = "Sets the order of scale, rotate, and translate operations for the collision geometry transform."
op_name.par.Rord.help = "Sets the order of rotation operations for the collision geometry transform."
op_name.par.Tx.help = "Translation of the collision geometry in world space."
op_name.par.Rx.help = "Rotation of the collision geometry in degrees."
op_name.par.Sx.help = "Scale of the collision geometry per axis."
op_name.par.Px.help = "Pivot point for the collision geometry transform."
op_name.par.Scale.help = "Uniform scale factor applied to the collision geometry."
op_name.par.Displaygeo.help = "Shows the collision geometry in the viewport for visualization."
op_name.par.Displaycolorr.help = "Display color for the collision geometry visualization."
op_name.par.Enableselfcollision.help = "Enable collision detection between different parts of the same soft body as well as between different geometries."
op_name.par.Maxdistance.help = "Maximum distance for neighbor search when using distance-based neighbors."
op_name.par.Distribution.help = "Distribution method for neighbor selection."
op_name.par.Maxneighbors.help = "Maximum number of neighbors to consider for self-collision per point."

# Page: Forces
op_name.par.Gravitymultiplier.help = "Multiplier for the gravity force."
op_name.par.Velocitydamping.help = "Global velocity damping to reduce motion over time. Range 0-1."
op_name.par.Staticthreshold.help = "Velocity threshold below which static friction is applied."
op_name.par.Dynamicscale.help = "Scale factor for dynamic friction forces."
op_name.par.Enableexternal.help = "Enable friction with external collision geometry."
op_name.par.Enableself.help = "Enable friction for self-collisions."
op_name.par.Groundstaticscale.help = "Static friction scale for ground collisions."
op_name.par.Grounddynamicscale.help = "Dynamic friction scale for ground collisions."
op_name.par.Enablegrabber.help = "Enable interactive grabber tool for manipulating points."
op_name.par.Grab.help = "Momentary button to activate grabbing."
op_name.par.Grabpositionx.help = "Position of the grabber in world space."
op_name.par.Grabradiusx.help = "Radius of the grabber influence sphere."
op_name.par.Grabstrength.help = "Strength of the grabber force applied to particles."
op_name.par.Transitionrange.help = "Range of the transition falloff from the grabber edge."
op_name.par.Transitionalign.help = "Alignment offset for the transition falloff."
op_name.par.Transitiontype.help = "Interpolation curve type for the transition falloff."
op_name.par.Displaygrabber.help = "Visualize the grabber sphere in the viewport."
op_name.par.Visgrabbedpoints.help = "Highlight points currently affected by the grabber."

# Page: Advanced
op_name.par.Enablemaxacc.help = "Enable maximum acceleration limiting to prevent instability."
op_name.par.Maxacceleration.help = "Maximum allowed acceleration magnitude."
op_name.par.Limitaccel.help = "Apply acceleration limiting during velocity update step."
op_name.par.Fallbackcollision.help = "Use first order integration when collisions are detected for improved stability."

print("Soft-Body parameter help text updated successfully!")
